repos:
  - repo: https://git.greenshadecapital.site/actions/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://git.greenshadecapital.site/actions/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://git.greenshadecapital.site/actions/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        args: ["--strict", "--ignore-missing-imports"]
